#############################################################################
# Makefile for building: LMDB.app/Contents/MacOS/LMDB
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  LMDB.pro
# Template: app
# Command: /Applications/Qt/5.8/clang_64/bin/qmake -o Makefile LMDB.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt/5.8/clang_64/mkspecs/macx-clang -F/Applications/Qt/5.8/clang_64/lib
QMAKE         = /Applications/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LMDB1.0.0
DISTDIR = /Users/vanpana/Google\ Drive/Uni/An\ 1/Semestrul\ 2\ -\ Mac/OOP/LMDB/.tmp/LMDB1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Applications/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.8/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		common/array.cpp \
		common/counter.cpp \
		common/util.cpp \
		domain/entities.cpp \
		domain/validator.cpp \
		repository/repository.cpp \
		repository/watchlist.cpp \
		ui/console.cpp \
		adminmode.cpp \
		usermode.cpp \
		chart.cpp \
		qcustomplot.cpp \
		MovieTableModel.cpp moc_mainwindow.cpp \
		moc_adminmode.cpp \
		moc_usermode.cpp \
		moc_chart.cpp \
		moc_qcustomplot.cpp
OBJECTS       = main.o \
		mainwindow.o \
		array.o \
		counter.o \
		util.o \
		entities.o \
		validator.o \
		repository.o \
		watchlist.o \
		console.o \
		adminmode.o \
		usermode.o \
		chart.o \
		qcustomplot.o \
		MovieTableModel.o \
		moc_mainwindow.o \
		moc_adminmode.o \
		moc_usermode.o \
		moc_chart.o \
		moc_qcustomplot.o
DIST          = data/movie_database.csv \
		data/movies_backup.csv \
		data/watchlist.csv \
		data/watchlist.html \
		/Applications/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		/Users/vanpana/.qmake.stash \
		/Applications/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		LMDB.pro mainwindow.h \
		common/array.h \
		common/counter.h \
		common/util.h \
		controller/controller.h \
		domain/entities.h \
		domain/validator.h \
		repository/repository.h \
		repository/watchlist.h \
		ui/console.h \
		adminmode.h \
		usermode.h \
		chart.h \
		qcustomplot.h \
		MovieTableModel.h main.cpp \
		mainwindow.cpp \
		common/array.cpp \
		common/counter.cpp \
		common/util.cpp \
		domain/entities.cpp \
		domain/validator.cpp \
		repository/repository.cpp \
		repository/watchlist.cpp \
		ui/console.cpp \
		adminmode.cpp \
		usermode.cpp \
		chart.cpp \
		qcustomplot.cpp \
		MovieTableModel.cpp
QMAKE_TARGET  = LMDB
DESTDIR       = 
TARGET        = LMDB.app/Contents/MacOS/LMDB


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_adminmode.h ui_usermode.h ui_chart.h $(OBJECTS)  
	@test -d LMDB.app/Contents/MacOS/ || mkdir -p LMDB.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LMDB.pro /Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		/Users/vanpana/.qmake.stash \
		/Applications/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		LMDB.pro \
		/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile LMDB.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Applications/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.8/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.8/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.8/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
/Users/vanpana/.qmake.stash:
/Applications/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.8/clang_64/mkspecs/features/lex.prf:
LMDB.pro:
/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile LMDB.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

LMDB.app/Contents/PkgInfo: 
	@test -d LMDB.app/Contents || mkdir -p LMDB.app/Contents
	@$(DEL_FILE) LMDB.app/Contents/PkgInfo
	@echo "APPL????" > LMDB.app/Contents/PkgInfo
LMDB.app/Contents/Resources/empty.lproj: 
	@test -d LMDB.app/Contents/Resources || mkdir -p LMDB.app/Contents/Resources
	@touch LMDB.app/Contents/Resources/empty.lproj
	
LMDB.app/Contents/Info.plist: 
	@test -d LMDB.app/Contents || mkdir -p LMDB.app/Contents
	@$(DEL_FILE) LMDB.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,vanpana.LMDB,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,LMDB,g" -e "s,@LIBRARY@,LMDB,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >LMDB.app/Contents/Info.plist

all: Makefile \
		LMDB.app/Contents/PkgInfo \
		LMDB.app/Contents/Resources/empty.lproj \
		LMDB.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Applications/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h common/array.h common/counter.h common/util.h controller/controller.h domain/entities.h domain/validator.h repository/repository.h repository/watchlist.h ui/console.h adminmode.h usermode.h chart.h qcustomplot.h MovieTableModel.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp common/array.cpp common/counter.cpp common/util.cpp domain/entities.cpp domain/validator.cpp repository/repository.cpp repository/watchlist.cpp ui/console.cpp adminmode.cpp usermode.cpp chart.cpp qcustomplot.cpp MovieTableModel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui adminmode.ui usermode.ui chart.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r LMDB.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Applications/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Applications/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_adminmode.cpp moc_usermode.cpp moc_chart.cpp moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_adminmode.cpp moc_usermode.cpp moc_chart.cpp moc_qcustomplot.cpp
moc_mainwindow.cpp: /Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		controller/controller.h \
		mainwindow.h \
		moc_predefs.h \
		/Applications/Qt/5.8/clang_64/bin/moc
	/Applications/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/vanpana/Google Drive/Uni/An 1/Semestrul 2 - Mac/OOP/LMDB' -I/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt/5.8/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_adminmode.cpp: /Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		controller/controller.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QListWidget \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		adminmode.h \
		moc_predefs.h \
		/Applications/Qt/5.8/clang_64/bin/moc
	/Applications/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/vanpana/Google Drive/Uni/An 1/Semestrul 2 - Mac/OOP/LMDB' -I/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt/5.8/clang_64/lib adminmode.h -o moc_adminmode.cpp

moc_usermode.cpp: /Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		repository/watchlist.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		controller/controller.h \
		repository/repository.h \
		domain/validator.h \
		usermode.h \
		moc_predefs.h \
		/Applications/Qt/5.8/clang_64/bin/moc
	/Applications/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/vanpana/Google Drive/Uni/An 1/Semestrul 2 - Mac/OOP/LMDB' -I/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt/5.8/clang_64/lib usermode.h -o moc_usermode.cpp

moc_chart.cpp: /Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		controller/controller.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		chart.h \
		moc_predefs.h \
		/Applications/Qt/5.8/clang_64/bin/moc
	/Applications/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/vanpana/Google Drive/Uni/An 1/Semestrul 2 - Mac/OOP/LMDB' -I/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt/5.8/clang_64/lib chart.h -o moc_chart.cpp

moc_qcustomplot.cpp: /Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		qcustomplot.h \
		moc_predefs.h \
		/Applications/Qt/5.8/clang_64/bin/moc
	/Applications/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/vanpana/Google Drive/Uni/An 1/Semestrul 2 - Mac/OOP/LMDB' -I/Applications/Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt/5.8/clang_64/lib qcustomplot.h -o moc_qcustomplot.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_adminmode.h ui_usermode.h ui_chart.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_adminmode.h ui_usermode.h ui_chart.h
ui_mainwindow.h: mainwindow.ui \
		/Applications/Qt/5.8/clang_64/bin/uic
	/Applications/Qt/5.8/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_adminmode.h: adminmode.ui \
		/Applications/Qt/5.8/clang_64/bin/uic
	/Applications/Qt/5.8/clang_64/bin/uic adminmode.ui -o ui_adminmode.h

ui_usermode.h: usermode.ui \
		/Applications/Qt/5.8/clang_64/bin/uic
	/Applications/Qt/5.8/clang_64/bin/uic usermode.ui -o ui_usermode.h

ui_chart.h: chart.ui \
		/Applications/Qt/5.8/clang_64/bin/uic \
		qcustomplot.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QtNumeric
	/Applications/Qt/5.8/clang_64/bin/uic chart.ui -o ui_chart.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		controller/controller.h \
		tests/test_controller.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		controller/controller.h \
		ui_mainwindow.h \
		adminmode.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QListWidget \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		usermode.h \
		chart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

array.o: common/array.cpp common/array.h \
		domain/entities.h \
		common/counter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o array.o common/array.cpp

counter.o: common/counter.cpp common/counter.h \
		domain/entities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o counter.o common/counter.cpp

util.o: common/util.cpp common/util.h \
		domain/entities.h \
		common/counter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o common/util.cpp

entities.o: domain/entities.cpp domain/entities.h \
		common/counter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entities.o domain/entities.cpp

validator.o: domain/validator.cpp domain/validator.h \
		domain/entities.h \
		common/counter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validator.o domain/validator.cpp

repository.o: repository/repository.cpp repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		common/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repository.o repository/repository.cpp

watchlist.o: repository/watchlist.cpp repository/watchlist.h \
		domain/entities.h \
		common/counter.h \
		common/array.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o watchlist.o repository/watchlist.cpp

console.o: ui/console.cpp ui/console.h \
		controller/controller.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		common/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o ui/console.cpp

adminmode.o: adminmode.cpp adminmode.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		controller/controller.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QListWidget \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		ui_adminmode.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminmode.o adminmode.cpp

usermode.o: usermode.cpp usermode.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		repository/watchlist.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		controller/controller.h \
		repository/repository.h \
		domain/validator.h \
		ui_usermode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermode.o usermode.cpp

chart.o: chart.cpp chart.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		controller/controller.h \
		repository/repository.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		domain/validator.h \
		repository/watchlist.h \
		ui_chart.h \
		qcustomplot.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		common/util.h \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chart.o chart.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QtNumeric
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

MovieTableModel.o: MovieTableModel.cpp MovieTableModel.h \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QAbstractTableModel \
		/Applications/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		tests/test_watchlist.h \
		repository/watchlist.h \
		domain/entities.h \
		common/counter.h \
		common/array.h \
		repository/repository.h \
		domain/validator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieTableModel.o MovieTableModel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_adminmode.o: moc_adminmode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminmode.o moc_adminmode.cpp

moc_usermode.o: moc_usermode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usermode.o moc_usermode.cpp

moc_chart.o: moc_chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chart.o moc_chart.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

